### ISSUE TITLE
[Mobile] Meeting agenda 메뉴에서 터치가 너무 민감

### ISSUE THREAD

**Issue by sshtel** [wonder13662/magendas#1]
Meeting agenda 메뉴에서 터치로 스크롤 올리면 하위 메뉴들이 자꾸 클릭이 됩니다.
(Role, Speech 등)

![media-20151112](https://cloud.githubusercontent.com/assets/4931557/11119390/8621c78e-898c-11e5-92a5-6f352d1c56fe.png)

**Comment by wonder13662** [comment]
수정되었습니다. 스크롤 시의 간섭 현상도 수정되었습니다. 확인부탁드릴께요~
