### ISSUE TITLE
URL로 접속 시 아이피 주소로 바뀜.

### ISSUE THREAD

**Issue by sshtel** [wonder13662/magendas#31]
URL(magendas.com) 으로 접속 하면 url 주소창에 아이피가 그대로 노출됨.

url을 그대로 유지하도록 개선이 필요합니다.

**Comment by wonder13662** [comment]
이 문제는 도메인 구매를 제가 후이즈로 구입후, AWS에 사용하기 위해서 연동시 AWS의 도메인 관리 서비스인 Route53으로 이전이 불가해서 부득이하게 강제 포워딩으로 사용중이라서 그래요 ^^ 이전 가능 기간은 내년 1월 초입니다. 구매일로부터 60일은 바로 다른 도메인 관리 업체로의 이전이 불가하다고 하네요. ㅠㅠ

**Comment by wonder13662** [comment]
수정되었습니다. 도메인 이전 완료로 아래 도메인에서 모두 접근 가능합니다.
http://magendas.com
http://magendas.net
http://magendas-korea.com
